#!/usr/bin/env bash
# Generate CycloneDX SBOMs (software bills of materials) into sbom/.
#
#   sbom/vabbit.cdx.json         the Linux client (only modules linked into the binary)
#   sbom/vabbit-deploy.cdx.json  the Bunny deploy tool
#   sbom/edge.cdx.json           the edge script and its build tools
#
# Needs go, jq and cyclonedx-gomod (go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@v1.8.0).
# Output is deterministic (no timestamps or serial numbers) so CI can check it is current.
set -euo pipefail
cd "$(dirname "$0")/.."
GOMOD=${CYCLONEDX_GOMOD:-cyclonedx-gomod}
# License detection mislabels golang.org/x (the Go project's BSD-3-Clause license) and
# can't see this repo's LICENSE for the vabbit module that vabbit-deploy links; that
# module is ../client, so its hash would change with every client edit.
strip() {
  # GOVERSION is whichever Go built the SBOM, not something the binary depends on.
  jq -S 'del(.metadata.timestamp, .serialNumber, .metadata.tools)
    | .metadata.component.properties |= map(select(.name != "cdx:gomod:build:env:GOVERSION"))
    | .components |= map(if (.name | startswith("golang.org/x/")) then .evidence.licenses = [{license: {id: "BSD-3-Clause"}}] else . end)
    | .components |= map(if .name == "vabbit" then (.licenses = [{license: {id: "MIT"}}] | del(.hashes)) else . end)' >"$1"
}

gomod_app() { # module dir, main package, output
  local raw ver
  raw=$(cd "$1" && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "$GOMOD" app -json -licenses -noserial -main "$2" -output - 2>/dev/null)
  # The app's own version is a pseudo-version of the current commit; replace it so
  # the file only changes when dependencies do.
  ver=$(jq -r '.metadata.component.version' <<<"$raw")
  sed "s/$ver/source/g" <<<"$raw" | strip "$3"
}
gomod_app client cmd/vabbit sbom/vabbit.cdx.json
gomod_app deploy cmd/vabbit-deploy sbom/vabbit-deploy.cdx.json

# The edge script's only runtime dependency is the Bunny SDK, imported by URL;
# typescript and @types/bun are build-time only.
sdk=$(grep -o 'esm.sh/@bunny.net/edgescript-sdk@[0-9.]*' edge/src/main.ts | sed 's#esm.sh/##')
sdk_ver=${sdk##*@}
jq -n -S --arg sdkv "$sdk_ver" \
  --arg ts "$(jq -r '.devDependencies.typescript' edge/package.json)" \
  --arg tb "$(jq -r '.devDependencies["@types/bun"]' edge/package.json)" '{
  bomFormat: "CycloneDX", specVersion: "1.6", version: 1,
  metadata: {component: {type: "application", name: "vabbit-edge", "bom-ref": "vabbit-edge",
    licenses: [{license: {id: "MIT"}}]}},
  components: [
    {type: "library", name: "@bunny.net/edgescript-sdk", version: $sdkv, scope: "required",
     purl: "pkg:npm/%40bunny.net/edgescript-sdk@\($sdkv)", "bom-ref": "pkg:npm/%40bunny.net/edgescript-sdk@\($sdkv)",
     licenses: [{license: {id: "MIT"}}]},
    {type: "library", name: "typescript", version: $ts, scope: "excluded",
     purl: "pkg:npm/typescript@\($ts)", "bom-ref": "pkg:npm/typescript@\($ts)",
     licenses: [{license: {id: "Apache-2.0"}}]},
    {type: "library", name: "@types/bun", version: $tb, scope: "excluded",
     purl: "pkg:npm/%40types/bun@\($tb)", "bom-ref": "pkg:npm/%40types/bun@\($tb)",
     licenses: [{license: {id: "MIT"}}]}
  ]}' >sbom/edge.cdx.json

# Human-readable summary.
{
  echo "# Dependencies"
  echo
  echo "Generated by \`scripts/sbom.sh\` from the CycloneDX files in this folder. Do not edit."
  echo "The Go standard library (BSD-3-Clause) is linked into both Go binaries and not listed."
  echo
  for f in vabbit vabbit-deploy edge; do
    echo "## $f"
    echo
    echo "| Component | Version | License |"
    echo "|---|---|---|"
    jq -r '.components[]? | "| \(.name) | \(.version // "-") | \([(.licenses // .evidence.licenses // [])[] | .license | (.id // .name)] | join(", ") | if . == "" then "unknown" else . end) |"' "sbom/$f.cdx.json" | sort
    echo
  done
} >sbom/README.md
echo "SBOMs written to sbom/"
